apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    version: "9.2.0" 
    values:
      installCertmanager: false
      nginx-ingress:
        enabled: false
      global:
        appConfig:
          terraformState:
            enabled: true
          omniauth:
            enabled: true
            allowedSingleSignOn: ['openid_connect']
            autoLinkUser: ['openid_connect']
            syncProfileFromProvider: ['openid_connect']
            syncProfileAttributes: ['email']
            blockAutoCreatedUsers: false
            providers:
              - secret: gitlab-omniauth
                key: openid_connect
        hosts:
          domain: padugg.com # use a real domain here
        ingress:
          configureCertmanager: false
          class: nginx
          tls:
            secretName: wildcard-padugg-com-tls
